(function () {
  "use strict";
  let DATA = [...(window.PAST_DATA || []), ...(window.KNOWLEDGE_DATA || []), ...(window.STUDY_DATA || []).filter(x => x.type !== "past")];
  const STORAGE_KEY = "radrecall-morita-v1";
  const navItems = [
    ["home", "⌂", "ホーム"], ["past", "▣", "過去問"], ["flash", "▤", "一問一答"],
    ["reference", "◇", "参考問題"], ["review", "!", "要確認"]
  ];
  let state = loadState();
  let route = "home", session = null, sessionIndex = 0, selected = [], revealed = false;
  let referenceFormat = "all";

  function freshState() { return { cards: {}, history: [], streak: 0, lastStudyDate: null }; }
  function loadState() { try { return { ...freshState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch (_) { return freshState(); } }
  function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
  function cardState(id) { return state.cards[id] || { due: null, interval: 0, ease: 2.5, reps: 0, lapses: 0, status: "unseen", verified: false, flagged: false }; }
  function esc(s) { return String(s ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
  function todayKey(d = new Date()) {
    const y=d.getFullYear(), m=String(d.getMonth()+1).padStart(2,"0"), day=String(d.getDate()).padStart(2,"0");
    return `${y}-${m}-${day}`;
  }
  function dueNow(item) { const c = cardState(item.id); if(item.type==='past' && item.needsReview && !c.verified) return false; return !c.due || c.due <= todayKey(); }
  function typeName(t, item) {
    if (t === "reference" && item) return item.referenceFormat === "mcq" ? "参考問題・過去問方式" : "参考問題・一問一答";
    return ({past:"過去問",flash:"一問一答",reference:"参考問題"})[t] || t;
  }
  function toast(msg) { const el=document.getElementById("toast"); el.textContent=msg; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),1800); }

  function bytesFromBase64(s){const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
  async function decryptBank(passphrase){const enc=window.ENCRYPTED_DATA;const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytesFromBase64(enc.salt),iterations:enc.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytesFromBase64(enc.iv)},key,bytesFromBase64(enc.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
  function unlockView(message=''){document.getElementById('desktop-nav').innerHTML='';document.getElementById('mobile-nav').innerHTML='';document.getElementById('app').innerHTML=`<div class="unlock-page"><section class="card unlock-card"><span class="brand-mark">R</span><div class="eyebrow">PRIVATE STUDY SPACE</div><h1>RadRecall</h1><p>森田先生専用の学習データを開きます。</p><label>アクセスキー<input id="access-key" type="password" autocomplete="current-password" placeholder="アクセスキーを入力"></label><label class="remember"><input id="remember-key" type="checkbox" checked> この端末に記憶する</label>${message?`<div class="unlock-error">${esc(message)}</div>`:''}<button class="primary wide" id="unlock-button">学習を始める</button></section></div>`;document.getElementById('unlock-button').onclick=unlock;document.getElementById('access-key').onkeydown=e=>{if(e.key==='Enter')unlock()};document.getElementById('access-key').focus()}
  async function unlock(){const input=document.getElementById('access-key'),button=document.getElementById('unlock-button'),pass=input.value;if(!pass)return;button.disabled=true;button.textContent='確認中…';try{DATA=await decryptBank(pass);if(document.getElementById('remember-key').checked)localStorage.setItem('radrecall-access-key',pass);render()}catch(_){localStorage.removeItem('radrecall-access-key');unlockView('アクセスキーが違います。もう一度確認してください。')}}
  async function bootstrap(){if(!window.ENCRYPTED_DATA){render();return}const saved=localStorage.getItem('radrecall-access-key');if(saved){try{DATA=await decryptBank(saved);render();return}catch(_){localStorage.removeItem('radrecall-access-key')}}unlockView()}

  function renderNav() {
    const html = navItems.map(([r,i,l]) => `<button class="nav-btn ${route===r?'active':''}" data-route="${r}"><span class="nav-icon">${i}</span><span>${l}</span></button>`).join("");
    document.getElementById("desktop-nav").innerHTML=html; document.getElementById("mobile-nav").innerHTML=html;
    document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>navigate(b.dataset.route));
  }
  function navigate(next) { route=next; session=null; sessionIndex=0; selected=[]; revealed=false; render(); window.scrollTo(0,0); }
  function render() { renderNav(); const app=document.getElementById("app"); app.innerHTML = route==="home"?homeView():route==="review"?reviewView():studyLanding(route); bind(); }

  function homeView() {
    const due = DATA.filter(dueNow).length, done = state.history.filter(h=>h.date===todayKey()).length;
    const pct = Math.min(100, Math.round((done/Math.max(1,done+due))*100));
    const flags = DATA.filter(x=>cardState(x.id).flagged || x.needsReview).length;
    const recent = state.history.slice(-4).reverse();
    return `<div class="page"><div class="hero"><div><div class="eyebrow">PRIVATE STUDY SPACE</div><h1>おかえりなさい、森田先生</h1><p class="subtitle">今日も、忘れかけた知識から効率よく。</p></div><div class="date-chip">${new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</div></div>
    <div class="grid"><section class="card progress-card"><div class="ring" style="--value:${pct}"><b>${pct}<small>%</small></b></div><div class="progress-copy"><h2>今日の復習</h2><p>期限が来た問題を優先して出題します</p><div class="counts"><div class="count"><strong>${due}</strong><small>復習待ち</small></div><div class="count"><strong>${done}</strong><small>今日の回答</small></div></div></div></section>
    <section class="card streak-card"><span class="pill">継続記録</span><div class="metric">${state.streak}<small>日</small></div><p>短時間でも毎日触れることが定着への近道です。</p></section>
    ${modeCard("past","過","過去問モード","2022～2025年を反復復習","原文のまま",DATA.filter(x=>x.type==='past').length)}
    ${modeCard("flash","一","一問一答","レジュメの知識を即答練習","出典つき",DATA.filter(x=>x.type==='flash').length)}
    ${modeCard("reference","参","参考問題","一問一答と4択を別々に練習","2方式",DATA.filter(x=>x.type==='reference').length)}
    </div><div class="section-title"><h2>最近の学習</h2><small>この端末の記録</small></div><section class="card activity">${recent.length?recent.map(h=>`<div class="activity-row"><span class="pill">${typeName(h.type)}</span><div><strong>${esc(h.title)}</strong><small>評価：${esc(h.ratingLabel)}</small></div><small>${esc(h.date)}</small></div>`).join(""):`<div class="empty">まだ学習記録がありません。最初の問題に挑戦しましょう。</div>`}</section><div class="section-title"><h2>バックアップ</h2><small>機種変更・故障に備える</small></div><section class="card backup-card"><div><h3>学習記録を書き出す／復元する</h3><p>問題の進捗、復習予定、確認状況をJSONファイルに保存します。</p></div><div class="actions"><button class="primary" id="export-backup">書き出す</button><button class="ghost" id="import-backup">復元する</button></div></section></div>`;
  }
  function modeCard(route,tag,title,desc,badge,count){return `<section class="card mode-card"><span class="mode-tag">${tag}</span><h3>${title}</h3><p>${desc}</p><div class="mode-meta"><span>${badge}</span><strong>試作 ${count}問</strong></div><button class="primary wide" data-start="${route}">学習を始める</button></section>`}

  function studyLanding(type) {
    if (session) return studyView();
    const items=DATA.filter(x=>x.type===type), due=items.filter(dueNow).length;
    const labels={past:["過去問モード","2022～2025年の問題を、成績に応じた間隔で反復します。"],flash:["一問一答","レジュメに明記された知識だけを、引用つきで確認します。"],reference:["AI参考問題","過去問とレジュメを結び、同じ知識を2つの方式で確認します。"]}[type];
    const years=[...new Set(items.map(x=>x.year).filter(Boolean))];
    const refPicker = type==='reference' ? `<div class="reference-picker"><button class="reference-option" data-ref-format="flash"><span class="mode-tag">一</span><span><strong>参考問題・一問一答</strong><small>選択肢なしで思い出す</small></span></button><button class="reference-option" data-ref-format="mcq"><span class="mode-tag">4</span><span><strong>参考問題・過去問方式</strong><small>4択で本番形式に近く</small></span></button></div>` : '';
    const reviewCount=items.filter(x=>cardState(x.id).flagged||(x.type==='past'&&x.needsReview&&!cardState(x.id).verified)).length;
    return `<div class="page"><div class="eyebrow">${typeName(type)}</div><h1>${labels[0]}</h1><p class="subtitle">${labels[1]}</p>${refPicker}<div class="filter-row">${type==='past'?`<select id="year-filter"><option value="all">すべての年度</option>${years.map(y=>`<option>${y}</option>`).join('')}</select>`:''}<select id="category-filter"><option value="all">すべての分野</option>${[...new Set(items.map(x=>x.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><section class="card"><h2>今日のセット</h2><p class="subtitle">復習期限が来た問題を優先し、未学習問題を続けて出題します。</p><div class="grid"><div class="count" style="grid-column:span 4"><strong>${due}</strong><small>今日の復習</small></div><div class="count" style="grid-column:span 4"><strong>${items.length}</strong><small>収録問題数</small></div><div class="count" style="grid-column:span 4"><strong>${reviewCount}</strong><small>要確認</small></div></div><div class="actions"><button class="primary" id="start-session">今日の学習を始める</button><button class="ghost" id="start-all">全問題から練習</button></div></section></div>`;
  }
  function startSession(type, all=false){let items=DATA.filter(x=>x.type===type);const yf=document.getElementById('year-filter')?.value,cf=document.getElementById('category-filter')?.value;if(type==='reference'&&referenceFormat!=='all')items=items.filter(x=>x.referenceFormat===referenceFormat);if(yf&&yf!=='all')items=items.filter(x=>String(x.year)===yf);if(cf&&cf!=='all')items=items.filter(x=>x.category===cf);const due=items.filter(dueNow);session=(all?items:(due.length?due:items)).slice().sort((a,b)=>(cardState(a.id).due||'0000').localeCompare(cardState(b.id).due||'0000'));sessionIndex=0;selected=[];revealed=false;render();}
  function studyView(){if(!session.length)return `<div class="page empty"><span class="big">✓</span>対象の問題がありません。</div>`;if(sessionIndex>=session.length)return sessionDone();const q=session[sessionIndex],cs=cardState(q.id),isChoice=Array.isArray(q.choices);return `<div class="study-wrap"><div class="study-top"><button data-back="${q.type}">← 一覧</button><strong>${sessionIndex+1} / ${session.length}</strong><span class="pill">${typeName(q.type,q)}</span></div><div class="progress-line"><span style="width:${((sessionIndex+1)/session.length)*100}%"></span></div><section class="card question-card"><div class="question-meta">${q.year?`<span class="pill">${q.year}年 第${q.number}問</span>`:''}<span class="pill">${esc(q.category)}</span>${q.origin?`<span class="pill">元問題：${esc(q.origin)}</span>`:''}${!cs.verified?'<span class="pill">未確認</span>':''}</div><h2 class="question">${esc(q.prompt)}</h2>${isChoice?choicesHtml(q):flashHtml()}${revealed?answerHtml(q):''}${!revealed?`<div class="actions"><button class="secondary wide" id="reveal" ${isChoice&&!selected.length?'disabled':''}>答えを見る</button></div>`:''}</section></div>`}
  function choicesHtml(q){return `<div class="choices">${q.choices.map((c,i)=>{let cl=selected.includes(i)?'selected':'';if(revealed&&q.answer.includes(i))cl='correct';else if(revealed&&selected.includes(i))cl='wrong';return `<button class="choice ${cl}" data-choice="${i}" ${revealed?'disabled':''}><span class="choice-letter">${String.fromCharCode(97+i)}</span><span>${esc(c)}</span></button>`}).join('')}</div>`}
  function flashHtml(){return revealed?'':`<div class="flash-placeholder">頭の中で答えてから「答えを見る」を押してください</div>`}
  function answerHtml(q){const cs=cardState(q.id);const notes=q.choiceNotes?`<div class="choice-notes">${q.choiceNotes.map((n,i)=>`<p><b>${String.fromCharCode(97+i)}</b>${esc(n)}</p>`).join('')}</div>`:'';return `<div class="answer-box"><strong>正解</strong><b>${esc(q.answerText)}</b></div><p class="explanation">${esc(q.explanation)}</p>${notes}<details class="source"><summary>根拠を見る</summary><div class="source-content"><b>${esc(q.source.name)}</b><span>${esc(q.source.page)}</span><div class="quote">「${esc(q.source.quote)}」</div></div></details><div class="actions"><button class="ghost" id="approve">✓ 問題なし</button><button class="ghost" id="flag">${cs.flagged?'✓ あとで確認に追加済み':'! あとで確認'}</button></div><div class="ratings"><button class="rating rating-1" data-rating="1">忘れた<small>すぐ復習</small></button><button class="rating rating-2" data-rating="2">あやしい<small>短く</small></button><button class="rating rating-3" data-rating="3">わかった<small>標準</small></button><button class="rating rating-4" data-rating="4">完璧<small>長く</small></button></div>`}
  function sessionDone(){return `<div class="study-wrap"><section class="card empty"><span class="big">✓</span><h2>今日のセット完了</h2><p>学習記録と次回復習日を保存しました。</p><div class="actions" style="justify-content:center"><button class="primary" data-route="home">ホームへ戻る</button><button class="ghost" data-restart="${route}">もう一度</button></div></section></div>`}

  function schedule(q,rating){const old=cardState(q.id), next={...old};const factors={1:0,2:.55,3:1,4:1.65};if(rating===1){next.interval=0;next.lapses=(old.lapses||0)+1;next.ease=Math.max(1.3,(old.ease||2.5)-.2)}else if(old.reps===0){next.interval=rating===2?1:rating===3?3:7}else if(old.reps===1){next.interval=Math.max(1,Math.round((old.interval||1)*(rating===2?1.5:rating===3?2.5:4)))}else{next.interval=Math.max(1,Math.round((old.interval||1)*(old.ease||2.5)*factors[rating]));next.ease=Math.min(3,Math.max(1.3,(old.ease||2.5)+(rating===2?-.12:rating===4?.1:0)))}next.reps=(old.reps||0)+1;const d=new Date();if(rating===1)d.setMinutes(d.getMinutes()+10);else d.setDate(d.getDate()+next.interval);next.due=rating===1?todayKey():todayKey(d);next.status='learning';state.cards[q.id]=next;updateStreak();const labels=['','忘れた','あやしい','わかった','完璧'];state.history.push({id:q.id,type:q.type,title:q.year?`${q.year}年第${q.number}問`:q.prompt.slice(0,22),rating,ratingLabel:labels[rating],date:todayKey()});saveState();sessionIndex++;selected=[];revealed=false;render();}
  function updateStreak(){const t=todayKey();if(state.lastStudyDate===t)return;const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastStudyDate===todayKey(y)?state.streak+1:1;state.lastStudyDate=t;}
  function reviewView(){const flagged=DATA.filter(x=>cardState(x.id).flagged||(x.type==='past'&&x.needsReview&&!cardState(x.id).verified));return `<div class="page"><div class="eyebrow">QUALITY CHECK</div><h1>要確認の問題</h1><p class="subtitle">学習中に保留した問題と、解答例が曖昧な問題です。</p><div class="review-list">${flagged.length?flagged.map(q=>`<section class="card review-item"><div><div class="question-meta"><span class="pill">${typeName(q.type,q)}</span>${q.year?`<span class="pill">${q.year}年 第${q.number}問</span>`:''}</div><strong>${esc(q.prompt)}</strong><p>${esc(q.source.name)}・${esc(q.source.page)}</p></div><button class="ghost" data-unflag="${q.id}">${q.type==='past'&&q.needsReview?'資料上の要確認':'確認済みにする'}</button></section>`).join(''):`<section class="card empty"><span class="big">✓</span>要確認問題はありません。</section>`}</div></div>`}
  function exportBackup(){const payload={app:'RadRecall',version:1,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RadRecall_backup_${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('バックアップを書き出しました')}
  function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result);if(payload.app!=='RadRecall'||!payload.state)throw Error('invalid');state={...freshState(),...payload.state};saveState();toast('学習記録を復元しました');render()}catch(_){toast('RadRecallのバックアップを選んでください')}};reader.readAsText(file)}
  function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>navigate(b.dataset.start));document.querySelectorAll('[data-ref-format]').forEach(b=>b.onclick=()=>{referenceFormat=b.dataset.refFormat;startSession('reference',true)});document.getElementById('start-session')?.addEventListener('click',()=>startSession(route));document.getElementById('start-all')?.addEventListener('click',()=>startSession(route,true));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>navigate(b.dataset.back));document.querySelectorAll('[data-restart]').forEach(b=>b.onclick=()=>{session=null;startSession(b.dataset.restart,true)});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.choice),q=session[sessionIndex];if(q.answer.length===1)selected=[i];else selected=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i];render()});document.getElementById('reveal')?.addEventListener('click',()=>{revealed=true;render()});document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>schedule(session[sessionIndex],Number(b.dataset.rating)));document.getElementById('approve')?.addEventListener('click',()=>{const q=session[sessionIndex],c=cardState(q.id);state.cards[q.id]={...c,verified:true,flagged:false};saveState();toast('確認済みにしました');render()});document.getElementById('flag')?.addEventListener('click',()=>{const q=session[sessionIndex],c=cardState(q.id);state.cards[q.id]={...c,flagged:!c.flagged};saveState();toast(!c.flagged?'あとで確認に追加しました':'確認リストから外しました');render()});document.querySelectorAll('[data-unflag]').forEach(b=>b.onclick=()=>{const q=DATA.find(x=>x.id===b.dataset.unflag);if(q.type==='past'&&q.needsReview){toast('解答例自体が要確認の問題です')}else{const c=cardState(q.id);state.cards[q.id]={...c,flagged:false,verified:true};saveState();render()}});document.getElementById('export-backup')?.addEventListener('click',exportBackup);document.getElementById('import-backup')?.addEventListener('click',()=>document.getElementById('backup-file').click());document.getElementById('backup-file').onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=''}}
  if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
  bootstrap();
})();
